INSERT INTO STUDENT_TBL ( STUDENT_NAME, STUDENT_JPA) VALUES ('VIJAYSEKHAR', 1.0);
INSERT INTO STUDENT_TBL ( STUDENT_NAME, STUDENT_JPA) VALUES ('KRISHNA', 1.0);
INSERT INTO STUDENT_TBL ( STUDENT_NAME, STUDENT_JPA) VALUES ('RAJASEKHAR', 1.0);
INSERT INTO STUDENT_TBL ( STUDENT_NAME, STUDENT_JPA) VALUES ('PAWAN', 1.0);

