INSERT INTO STUDENT_TBL ( ID, STUDENT_NAME, STUDENT_JPA) VALUES (1, 'VIJAYSEKHAR', 1.0);
INSERT INTO STUDENT_TBL ( ID, STUDENT_NAME, STUDENT_JPA) VALUES (2, 'KRISHNA', 1.0);
INSERT INTO STUDENT_TBL ( ID, STUDENT_NAME, STUDENT_JPA) VALUES (3, 'RAJASEKHAR', 1.0);
INSERT INTO STUDENT_TBL ( ID, STUDENT_NAME, STUDENT_JPA) VALUES (4, 'PAWAN', 1.0);

INSERT INTO Cource_tbl (ID, courcename) VALUES (101, 'MCA');
INSERT INTO Cource_tbl (ID, courcename) VALUES (102, 'MBA');
INSERT INTO Cource_tbl (ID, courcename) VALUES (103, 'MSC');
INSERT INTO Cource_tbl (ID, courcename) VALUES (104, 'MPHIL');

